//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bbt1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Discount
    {
        public int d_id { get; set; }

        [StringLength(50, ErrorMessage = "活動標題最多只能輸入50個字")]
        [Required(ErrorMessage = "請輸入活動標題")]
        //[RegularExpression(@"^[\u4e00-\u9fa5],{0,}$", ErrorMessage = "活動標題只能輸入中文")]
        public string d_activity { get; set; }

        [RegularExpression(@"^[0-9]+(.[0-9]{1,1})?$", ErrorMessage = "只能輸入小數")]
        public Nullable<float> d_discount { get; set; }
        public Nullable<System.DateTime> d_startdate { get; set; }
        public Nullable<System.DateTime> d_enddate { get; set; }
        public Nullable<int> c_id { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
